[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[Settings]

[[headers]]
  for = "/nl/*"
  [headers.values]
    Content-Language = "nl"

[[headers]]
  for = "/en/*"
  [headers.values]
    Content-Language = "en"

[[headers]]
  for = "/be/*"
  [headers.values]
    Content-Language = "nl-BE"

[[headers]]
  for = "/de/*"
  [headers.values]
    Content-Language = "de"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
